
> metaverse-client@0.0.0 dev
> vite --port 5173 --host

Forced re-optimization of dependencies

  VITE v4.5.14  ready in 171 ms

  âžœ  Local:   https://localhost:5173/
  âžœ  Network: https://192.168.200.106:5173/
  âžœ  Network: https://172.17.0.1:5173/
5:03:37 AM [vite] warning: Duplicate key "mapCreatorId" in object literal
151|              mapCreatorId: map.creatorId,
152|              mapCreatedBy: map.createdBy,
153|              mapCreatorId: map.creator?.id,
   |              ^
154|              userId: user?.id,
155|              creatorIdMatch: map.creatorId === user?.id,

  Plugin: vite:esbuild
  File: /home/wh/working/complete/mini-area/client/src/pages/MetaverseEdit.jsx
5:03:37 AM [vite] warning: Duplicate key "mapCreatorId" in object literal
165|                mapCreatorId: map.creatorId,
166|                mapCreatedBy: map.createdBy,
167|                mapCreatorId: map.creator?.id,
   |                ^
168|                userId: user?.id,
169|                userName: user?.username

  Plugin: vite:esbuild
  File: /home/wh/working/complete/mini-area/client/src/pages/MetaverseEdit.jsx
5:04:54 AM [vite] hmr update /src/components/PersonalShop.jsx
5:05:02 AM [vite] hmr update /src/components/PersonalShop.jsx
5:09:02 AM [vite] hmr update /src/components/PersonalShop.jsx
5:09:14 AM [vite] hmr update /src/components/PersonalShop.jsx
5:09:21 AM [vite] hmr update /src/components/PersonalShop.jsx
5:09:28 AM [vite] hmr update /src/components/PersonalShop.jsx
5:09:35 AM [vite] hmr update /src/components/PersonalShop.jsx
5:09:43 AM [vite] hmr update /src/components/PersonalShop.jsx
5:10:43 AM [vite] hmr update /src/components/PersonalShop.jsx
5:11:03 AM [vite] hmr update /src/components/PersonalShop.jsx
5:11:26 AM [vite] hmr update /src/components/PersonalShop.jsx
5:11:52 AM [vite] .env.example.tmp.25830.1758139912013 changed, restarting server...
5:11:52 AM [vite] .env.example changed, restarting server...
Forced re-optimization of dependencies
Port 5173 is in use, trying another one...
5:11:52 AM [vite] server restarted.

  âžœ  Local:   https://localhost:5174/
  âžœ  Network: https://192.168.200.106:5174/
  âžœ  Network: https://172.17.0.1:5174/
6:08:47 AM [vite] .env.example.tmp.25830.1758143327178 changed, restarting server...
6:08:47 AM [vite] .env.example changed, restarting server...
Forced re-optimization of dependencies
Port 5173 is in use, trying another one...
6:08:47 AM [vite] server restarted.

  âžœ  Local:   https://localhost:5174/
  âžœ  Network: https://192.168.200.106:5174/
  âžœ  Network: https://172.17.0.1:5174/
Error:   Failed to scan for dependencies from entries:
  /home/wh/working/complete/mini-area/client/index.html

  [31mâœ˜ [41;31m[[41;97mERROR[41;31m][0m [1mFailed to resolve entry for package "@portone/browser-sdk". The package may have incorrect main/module/exports specified in its package.json: Missing "." specifier in "@portone/browser-sdk" package[0m [1m[35m[plugin vite:dep-scan][0m

    node_modules/esbuild/lib/main.js:1373:21:
[37m      1373 â”‚         let result = [32m[37mawait callback({
           â•µ                      [32m^[0m

    at packageEntryFailure (file:///home/wh/working/complete/mini-area/client/node_modules/vite/dist/node/chunks/dep-827b23df.js:28726:11)
    at resolvePackageEntry (file:///home/wh/working/complete/mini-area/client/node_modules/vite/dist/node/chunks/dep-827b23df.js:28721:9)
    at tryNodeResolve (file:///home/wh/working/complete/mini-area/client/node_modules/vite/dist/node/chunks/dep-827b23df.js:28454:20)
    at Context.resolveId (file:///home/wh/working/complete/mini-area/client/node_modules/vite/dist/node/chunks/dep-827b23df.js:28213:28)
    at Object.resolveId (file:///home/wh/working/complete/mini-area/client/node_modules/vite/dist/node/chunks/dep-827b23df.js:44280:64)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async resolve (file:///home/wh/working/complete/mini-area/client/node_modules/vite/dist/node/chunks/dep-827b23df.js:44585:26)
    at async file:///home/wh/working/complete/mini-area/client/node_modules/vite/dist/node/chunks/dep-827b23df.js:44762:34
    at async requestCallbacks.on-resolve (/home/wh/working/complete/mini-area/client/node_modules/esbuild/lib/main.js:1373:22)
    at async handleRequest (/home/wh/working/complete/mini-area/client/node_modules/esbuild/lib/main.js:729:13)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1292:20:
[37m      1292 â”‚       let promise = [32m[37msetup({
           â•µ                     [32m^[0m

    at setup (file:///home/wh/working/complete/mini-area/client/node_modules/vite/dist/node/chunks/dep-827b23df.js:44752:19)
    at handlePlugins (/home/wh/working/complete/mini-area/client/node_modules/esbuild/lib/main.js:1292:21)
    at buildOrContextImpl (/home/wh/working/complete/mini-area/client/node_modules/esbuild/lib/main.js:978:5)
    at Object.buildOrContext (/home/wh/working/complete/mini-area/client/node_modules/esbuild/lib/main.js:786:5)
    at /home/wh/working/complete/mini-area/client/node_modules/esbuild/lib/main.js:2186:68
    at new Promise (<anonymous>)
    at Object.context (/home/wh/working/complete/mini-area/client/node_modules/esbuild/lib/main.js:2186:27)
    at Object.context (/home/wh/working/complete/mini-area/client/node_modules/esbuild/lib/main.js:2026:58)
    at prepareEsbuildScanner (file:///home/wh/working/complete/mini-area/client/node_modules/vite/dist/node/chunks/dep-827b23df.js:44535:26)
    at async file:///home/wh/working/complete/mini-area/client/node_modules/vite/dist/node/chunks/dep-827b23df.js:45191:38

  The plugin "vite:dep-scan" was triggered by this import

    src/services/paymentService.js:2:24:
[37m      2 â”‚ import { PortOne } from [32m'@portone/browser-sdk'[37m;
        â•µ                         [32m~~~~~~~~~~~~~~~~~~~~~~[0m


    at failureErrorWithLog (/home/wh/working/complete/mini-area/client/node_modules/esbuild/lib/main.js:1649:15)
    at /home/wh/working/complete/mini-area/client/node_modules/esbuild/lib/main.js:1058:25
    at runOnEndCallbacks (/home/wh/working/complete/mini-area/client/node_modules/esbuild/lib/main.js:1484:45)
    at buildResponseToResult (/home/wh/working/complete/mini-area/client/node_modules/esbuild/lib/main.js:1056:7)
    at /home/wh/working/complete/mini-area/client/node_modules/esbuild/lib/main.js:1068:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (/home/wh/working/complete/mini-area/client/node_modules/esbuild/lib/main.js:1067:54)
    at handleRequest (/home/wh/working/complete/mini-area/client/node_modules/esbuild/lib/main.js:729:19)
    at handleIncomingPacket (/home/wh/working/complete/mini-area/client/node_modules/esbuild/lib/main.js:755:7)
    at Socket.readFromStdout (/home/wh/working/complete/mini-area/client/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:189:23)
8:03:45 AM [vite] .env.tmp.25830.1758150225283 changed, restarting server...
8:03:45 AM [vite] .env changed, restarting server...
Forced re-optimization of dependencies
Port 5173 is in use, trying another one...
8:03:45 AM [vite] server restarted.

  âžœ  Local:   https://localhost:5174/
  âžœ  Network: https://192.168.200.106:5174/
  âžœ  Network: https://172.17.0.1:5174/
